### ISSUE TITLE
Display number of remaining goals

### ISSUE THREAD

**Issue by FredericLeRoux** [dEAduction/dEAduction#15]
On the right hand side of the target area, we could display the number of remaining goals. So for example if the target has form `P AND Q`and the AND button is clicked, the target would become `P`but has the same time the number of targets would change from `1`to `2`.

**Comment by FredericLeRoux** [comment]
TODO: add a two counters,
- total number of goals,
- number of current goal

**Comment by FredericLeRoux** [comment]
The counters are done.

**Comment by kryzar** [comment]
Resolved by @FredericLeRoux.
