### ISSUE TITLE
Weird context

### ISSUE THREAD

**Issue by FredericLeRoux** [dEAduction/dEAduction#71]
### Bug description

Sometimes the displayed context is weird, not related to what should be displayed. Actually the displayed context seems to correspond to a previous exercise.

### How to reproduce the bug

Not easy. My guess is that this happens because deaduction is unable to discriminate Lean server's responses according to the request number, and thus it may happen that deaduction mistake an old response for the one it is waiting for.
Since deaduction discriminate responses according to the line number in the lean file, this may happen only when a line number coincidence occurs.

Note that this seems to happen even if Lean server is stopped and started again between two exercises (to be checked).

### Environment
- OS and OS version: unrelated
- d∃∀duction version (or commit ID): 5f88db4a0321e4b4b73ca66173eda95fc0eef493

### Fix ideas

- Quick bad fix: artificially add 100 lines times number of exercise in the preamble of the Lean virtual file...
- Reasonnable fix: find a way to empty Lean's responses queue before starting a new exercise.

### Submission checklist

1. [x] d∃∀duction is up-to-date and this bug is in the latest version.
2. [x] I've checked that no-one reported this problem by browsing [other
   issues](https://github.com/dEAduction/dEAduction/issues).
3. [x] This issue deals with one and only one issue (if you have multiple
   issues, please open multiple issues).
4. [x] I correctly labeled my issue (see commented rules below).
5. [ ] I want to fix this bug. (Check if you do, no judgement if you do not!)

**Comment by kryzar** [comment]
When you get this bug again, could you please provide screenshots?

**Comment by FredericLeRoux** [comment]
Update 1: screenshot
![image](https://user-images.githubusercontent.com/34716801/113716873-4ee45580-96eb-11eb-9638-a5e14ffd2d3c.png)
Bug description by user for the screenshot: 
"dans l’exercice A ∩ B = A ∪ B ⇒ A = B (quand l’intersection égale à l’union)
A la première étape, en cliquant sur ⇒, voici la fenêtre qui apparait (c’est l’hypothèse du contexte qui cloche).
Plus curieux encore, si je reviens en arrière puis que je retourne à l’étape présente, le bug disparait… De même si j’essaie de transformer cette fausse hypothèse avec des définitions par exemple..."

**Comment by FredericLeRoux** [comment]
Update 2: bad fix done...

**Comment by FredericLeRoux** [comment]
Update 3: another screenshot (_before_ the bad fix). Is this the same bug?!
(At least this is also a non deterministic bug)
![image](https://user-images.githubusercontent.com/34716801/113717171-a387d080-96eb-11eb-96e7-3549b94f6ccd.png)

**Comment by FredericLeRoux** [comment]
A priori this should be settled. Now every request to Lean has the same file name. This prevents Lean from sending again the aswers to old requests.
