### ISSUE TITLE
Flash button during redo

### ISSUE THREAD

**Issue by FredericLeRoux** [dEAduction/dEAduction#73]
### Feature, enhancement or refactor description
During redo, the soft simulates pushing action buttons. Enhance this by making the button flash.

### Why is it useful
This should make the simulation more visible. Just simulating pushing the button does not catch the eye, especially on Linux where the button appearence does not change a lot.

### Implementation ideas, difficulties we may face
We should not choose something too flashy. Especially since this is not part of standard button behaviour.

### Submission checklist

1. [x] d∃∀duction is up-to-date and this feature does not exist in the latest
   version.
2. [x] I've checked that no-one proposed this feature before by browsing [other
   issues](https://github.com/dEAduction/dEAduction/issues).
3. [x] This issue deals with one and only one issue (if you have multiple
   issues, please open multiple issues).
4. [x] I correctly labeled my issue (see commented rules below).
5. [x] I want to implement this suggestion. (Check if yo do, no judgement if
   you do not!)

**Comment by FredericLeRoux** [comment]
Done!

**Comment by kryzar** [comment]
It's lovely to see some activity here. Congrats on closing an issue that's many  years old :heart:
